server {
    listen 80;
    client_max_body_size 150M;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://backend:8080;
    }

    location /audio/ {
        proxy_pass http://audio-server/audio/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
