services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    profiles: ["prod"]

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    profiles: ["prod"]

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  audio-server:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./audio-files:/usr/share/nginx/html/audio:ro

volumes:
  db-data:
